@startuml
'https://plantuml.com/class-diagram

class User{
- User id
- Username
- password
}

class Main_Library{

#Genre
#Rating


}
abstract class content{
- content id


}
class Movies{
- title
- duration
- director
- genre

}


class Series{
- title
+ getSeason()
-rating
- genre


}
class Seasons {
- title
- SeasonNumber
+ getEpisodes()
}
class Episodes {
- title
+ getEpisodes
-rating
-genre


}

@enduml